In [1]:
import pandas as pd
import numpy as np
import sklearn 
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler
import matplotlib as plt
import keras

Using TensorFlow backend.


In [2]:
file=pd.read_csv("dataset1.csv")

In [3]:
dummies=pd.get_dummies(file.kesimpulan)

In [4]:
file1=pd.concat([file,dummies],axis='columns')

In [5]:
file1

no id     berat  tingg  tinggi (m)  gender  berat ideal    kesimpulan  \
0        1   42.2400    160        1.60    Male        16.50  under weight   
1        2   43.4944    160        1.60    Male        16.99  under weight   
2        3   43.5200    160        1.60    Male        17.00        normal   
3        4   58.6240    160        1.60    Male        22.90        normal   
4        5   58.8800    160        1.60    Male        23.00   over weight   
5        6   69.0944    160        1.60    Male        26.99   over weight   
6        7   69.1200    160        1.60    Male        27.00      obesitas   
7        8   69.1456    160        1.60    Male        27.01      obesitas   
8        9   39.3750    150        1.50  Female        17.50  under weight   
9       10   40.4775    150        1.50  Female        17.99  under weight   
10      11   40.5000    150        1.50  Female        18.00        normal   
11      12   56.2275    150        1.50  Female        24.99        normal   
12      13   56.2500    150        1.50  Female        25.00   over weight   
13      14   60.7500    150        1.50  Female        27.00   over weight   
14      15   60.7725    150        1.50  Female        27.01      obesitas   
15      16   61.8750    150        1.50  Female        27.50      obesitas   
16      17   96.0000    174        1.74    Male        31.71      obesitas   
17      18   87.0000    189        1.89    Male        24.36   over weight   
18      19  110.0000    185        1.85  Female        32.14      obesitas   
19      20  104.0000    195        1.95  Female        27.35      obesitas   
20      21   61.0000    149        1.49    Male        27.48      obesitas   
21      22  104.0000    189        1.89    Male        29.11      obesitas   
22      23   92.0000    147        1.47    Male        42.57      obesitas   
23      24  111.0000    154        1.54    Male        46.80      obesitas   
24      25   90.0000    174        1.74    Male        29.73      obesitas   
25      26  103.0000    169        1.69  Female        36.06      obesitas   
26      27   81.0000    195        1.95    Male        21.30        normal   
27      28   80.0000    159        1.59  Female        31.64      obesitas   
28      29  101.0000    192        1.92  Female        27.40      obesitas   
29      30   51.0000    155        1.55    Male        21.23        normal   
..     ...       ...    ...         ...     ...          ...           ...   
486    488  142.0000    147        1.47    Male        65.71      obesitas   
487    489  112.0000    154        1.54    Male        47.23      obesitas   
488    490   65.0000    178        1.78  Female        20.52        normal   
489    491  153.0000    195        1.95    Male        40.24      obesitas   
490    492   79.0000    167        1.67  Female        28.33      obesitas   
491    493  131.0000    183        1.83    Male        39.12      obesitas   
492    494  142.0000    164        1.64  Female        52.80      obesitas   
493    495   64.0000    167        1.67    Male        22.95        normal   
494    496   55.0000    151        1.51  Female        24.12   over weight   
495    497  107.0000    147        1.47  Female        49.52      obesitas   
496    498  115.0000    155        1.55  Female        47.87      obesitas   
497    499  108.0000    172        1.72  Female        36.51      obesitas   
498    500   86.0000    142        1.42  Female        42.65      obesitas   
499    501   85.0000    146        1.46    Male        39.88      obesitas   
500    502  115.0000    188        1.88  Female        32.54      obesitas   
501    503  111.0000    173        1.73    Male        37.09      obesitas   
502    504  109.0000    160        1.60  Female        42.58      obesitas   
503    505   80.0000    187        1.87    Male        22.88        normal   
504    506  136.0000    198        1.98    Male        34.69      obesitas   
505    507  150.0000    179

In [6]:
dummies=pd.get_dummies(file.gender)
file1=pd.concat([file1,dummies],axis='columns')

In [7]:
file1=file1.drop(['no id','kesimpulan','tinggi (m)','gender','Female'],axis='columns')

In [8]:
file1.head()

berat  tingg  berat ideal  lari   normal  obesitas  over weight  \
0  42.2400    160        16.50      0       0         0            0   
1  43.4944    160        16.99      0       0         0            0   
2  43.5200    160        17.00     30       1         0            0   
3  58.6240    160        22.90     30       1         0            0   
4  58.8800    160        23.00     60       0         0            1   

   under weight  Male  
0             1     1  
1             1     1  
2             0     1  
3             0     1  
4             0     1

In [9]:
file1.columns = ['berat','tingg','berat ideal',
                     'lari','normal','obesitas','over weight','under weight','gender']
cols = file1.columns.tolist()
cols=['berat','tingg','gender','berat ideal','lari','normal','obesitas','over weight','under weight']
final=file1[cols]

In [10]:
final

berat  tingg  gender  berat ideal  lari  normal  obesitas  \
0     42.2400    160       1        16.50     0       0         0   
1     43.4944    160       1        16.99     0       0         0   
2     43.5200    160       1        17.00    30       1         0   
3     58.6240    160       1        22.90    30       1         0   
4     58.8800    160       1        23.00    60       0         0   
5     69.0944    160       1        26.99    60       0         0   
6     69.1200    160       1        27.00    90       0         1   
7     69.1456    160       1        27.01    90       0         1   
8     39.3750    150       0        17.50     0       0         0   
9     40.4775    150       0        17.99     0       0         0   
10    40.5000    150       0        18.00    30       1         0   
11    56.2275    150       0        24.99    30       1         0   
12    56.2500    150       0        25.00    60       0         0   
13    60.7500    150       0        27.00    60       0         0   
14    60.7725    150       0        27.01    90       0         1   
15    61.8750    150       0        27.50    90       0         1   
16    96.0000    174       1        31.71    90       0         1   
17    87.0000    189       1        24.36    60       0         0   
18   110.0000    185       0        32.14    90       0         1   
19   104.0000    195       0        27.35    90       0         1   
20    61.0000    149       1        27.48    90       0         1   
21   104.0000    189       1        29.11    90       0         1   
22    92.0000    147       1        42.57    90       0         1   
23   111.0000    154       1        46.80    90       0         1   
24    90.0000    174       1        29.73    90       0         1   
25   103.0000    169       0        36.06    90       0         1   
26    81.0000    195       1        21.30    30       1         0   
27    80.0000    159       0        31.64    90       0         1   
28   101.0000    192       0        27.40    90       0         1   
29    51.0000    155       1        21.23    30       1         0   
..        ...    ...     ...          ...   ...     ...       ...   
486  142.0000    147       1        65.71    90       0         1   
487  112.0000    154       1        47.23    90       0         1   
488   65.0000    178       0        20.52    30       1         0   
489  153.0000    195       1        40.24    90       0         1   
490   79.0000    167       0        28.33    90       0         1   
491  131.0000    183       1        39.12    90       0         1   
492  142.0000    164       0        52.80    90       0         1   
493   64.0000    167       1        22.95    30       1         0   
494   55.0000    151       0        24.12    60       0         0   
495  107.0000    147       0        49.52    90       0         1   
496  115.0000    155       0        47.87    90       0         1   
497  108.0000    172       0        36.51    90       0         1   
498   86.0000    142       0        42.65    90       0         1   
499   85.0000    146       1        39.88    90       0         1   
500  115.0000    188       0        32.54    90       0         1   
501  111.0000    173       1        37.09    90       0         1   
502  109.0000    160       0        42.58    90       0         1   
503   80.0000    187       1        22.88    30       1         0   
504  136.0000    198       1        34.69    90       0         1   
505  150.0000    179       0        46.82    90       0         1   
506   59.0000    164       0        21.94    30       1         0   
507  147.0000    146       0        68.96    90       0         1   
508   50.0000    198       0        12.75     0       0         0   
509   53.0000    170       0        18.34    30       1         0   
510   98.0000    152       1        42.42    90       0         1   
511  153.0000    150       0        68.00    90       0         1   
512  1

In [11]:
final.head()

berat  tingg  gender  berat ideal  lari  normal  obesitas  over weight  \
0  42.2400    160       1        16.50     0       0         0            0   
1  43.4944    160       1        16.99     0       0         0            0   
2  43.5200    160       1        17.00    30       1         0            0   
3  58.6240    160       1        22.90    30       1         0            0   
4  58.8800    160       1        23.00    60       0         0            1   

   under weight  
0             1  
1             1  
2             0  
3             0  
4             0

In [12]:
ms=MinMaxScaler()
ms.fit(final.iloc[:,:5])
final=ms.transform(final.iloc[:,:5])

In [13]:
final[:6,:]

array([[0.0237513 , 0.33898305, 1.        , 0.05673222, 0.        ],
       [0.03415047, 0.33898305, 1.        , 0.06414523, 0.        ],
       [0.03436269, 0.33898305, 1.        , 0.06429652, 0.33333333],
       [0.1595772 , 0.33898305, 1.        , 0.15355522, 0.33333333],
       [0.16169948, 0.33898305, 1.        , 0.15506808, 0.66666667],
       [0.24637845, 0.33898305, 1.        , 0.21543116, 0.66666667]])

In [14]:
y=final[:,4]

In [15]:
y[0:5]

array([0.        , 0.        , 0.33333333, 0.33333333, 0.66666667])

In [17]:
x=final[:,:4]
x

array([[0.0237513 , 0.33898305, 1.        , 0.05673222],
       [0.03415047, 0.33898305, 1.        , 0.06414523],
       [0.03436269, 0.33898305, 1.        , 0.06429652],
       ...,
       [0.80103627, 0.01694915, 0.        , 0.84205749],
       [0.4611399 , 0.16949153, 1.        , 0.44583964],
       [0.75958549, 0.55932203, 1.        , 0.46928896]])

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [19]:
x_train[1].shape

(4,)

In [20]:
x_train

array([[0.5357513 , 0.3220339 , 1.        , 0.42950076],
       [0.84248705, 0.08474576, 0.        , 0.82163389],
       [0.46943005, 0.86440678, 1.        , 0.20529501],
       ...,
       [0.0091399 , 0.16949153, 0.        , 0.07927383],
       [0.36165803, 0.66101695, 1.        , 0.198941  ],
       [0.51917098, 0.50847458, 0.        , 0.34099849]])

In [21]:
x_train.shape

(412, 4)

In [22]:
x_train[0,:3].shape

(3,)

In [23]:
y_train[0].shape

()

In [24]:
import keras as k
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras.optimizers import adam

In [25]:
model = Sequential()
model.add(Dense(10,input_shape=(4,)))
model.add(Activation('relu'))
model.add(Dense(5,))
model.add(Activation('relu'))
model.add(Dense(1))
model.add(Activation('relu'))

In [26]:
opt = adam(lr=1e-3, decay=1e-3 / 200)
model.compile(loss="mean_absolute_percentage_error",
              optimizer=opt,
              metrics=['accuracy'])

In [27]:
model.fit(x_train, y_train, validation_data=(x_test,y_test),
epochs=200, batch_size=8)



Train on 412 samples, validate on 104 samples
Epoch 1/200
412/412 [==============================] - 0s 1ms/step - loss: 4562655.0823 - acc: 0.0388 - val_loss: 3645119.2699 - val_acc: 0.0577
Epoch 2/200
412/412 [==============================] - 0s 150us/step - loss: 892267.5745 - acc: 0.0388 - val_loss: 86124.3320 - val_acc: 0.0577
Epoch 3/200
412/412 [==============================] - 0s 126us/step - loss: 42330.5441 - acc: 0.0388 - val_loss: 77.4937 - val_acc: 0.0577
Epoch 4/200
412/412 [==============================] - 0s 119us/step - loss: 79.2102 - acc: 0.0388 - val_loss: 824586.9023 - val_acc: 0.0577
Epoch 5/200
412/412 [==============================] - 0s 121us/step - loss: 229401.3029 - acc: 0.0388 - val_loss: 97009.1428 - val_acc: 0.0577
Epoch 6/200
412/412 [==============================] - 0s 121us/step - loss: 8229.1288 - acc: 0.0388 - val_loss: 75.8394 - val_acc: 0.0577
Epoch 7/200
412/412 [==============================] - 0s 124us/step - loss: 81.6667 - acc: 0.0388 

412/412 [==============================] - 0s 121us/step - loss: 82.2989 - acc: 0.0388 - val_loss: 79.2835 - val_acc: 0.0577
Epoch 58/200
412/412 [==============================] - 0s 129us/step - loss: 82.2960 - acc: 0.0388 - val_loss: 79.2805 - val_acc: 0.0577
Epoch 59/200
412/412 [==============================] - 0s 121us/step - loss: 82.2930 - acc: 0.0388 - val_loss: 79.2774 - val_acc: 0.0577
Epoch 60/200
412/412 [==============================] - 0s 124us/step - loss: 82.2900 - acc: 0.0388 - val_loss: 79.2743 - val_acc: 0.0577
Epoch 61/200
412/412 [==============================] - 0s 124us/step - loss: 82.2868 - acc: 0.0388 - val_loss: 79.2711 - val_acc: 0.0577
Epoch 62/200
412/412 [==============================] - 0s 124us/step - loss: 82.2836 - acc: 0.0388 - val_loss: 79.2678 - val_acc: 0.0577
Epoch 63/200
412/412 [==============================] - 0s 121us/step - loss: 82.2803 - acc: 0.0388 - val_loss: 79.2644 - val_acc: 0.0577
Epoch 64/200
412/412 [=========================

412/412 [==============================] - 0s 117us/step - loss: 81.8858 - acc: 0.0388 - val_loss: 78.8560 - val_acc: 0.0577
Epoch 117/200
412/412 [==============================] - 0s 112us/step - loss: 81.8717 - acc: 0.0388 - val_loss: 78.8415 - val_acc: 0.0577
Epoch 118/200
412/412 [==============================] - 0s 119us/step - loss: 81.8571 - acc: 0.0388 - val_loss: 78.8262 - val_acc: 0.0577
Epoch 119/200
412/412 [==============================] - 0s 117us/step - loss: 81.8420 - acc: 0.0388 - val_loss: 78.8108 - val_acc: 0.0577
Epoch 120/200
412/412 [==============================] - 0s 121us/step - loss: 81.8265 - acc: 0.0388 - val_loss: 78.7952 - val_acc: 0.0577
Epoch 121/200
412/412 [==============================] - 0s 117us/step - loss: 81.8107 - acc: 0.0388 - val_loss: 78.7788 - val_acc: 0.0577
Epoch 122/200
412/412 [==============================] - 0s 121us/step - loss: 81.7944 - acc: 0.0388 - val_loss: 78.7617 - val_acc: 0.0577
Epoch 123/200
412/412 [==================

412/412 [==============================] - 0s 117us/step - loss: 79.7320 - acc: 0.0388 - val_loss: 76.6792 - val_acc: 0.0577
Epoch 176/200
412/412 [==============================] - 0s 121us/step - loss: 79.6548 - acc: 0.0388 - val_loss: 76.6027 - val_acc: 0.0577
Epoch 177/200
412/412 [==============================] - 0s 124us/step - loss: 79.5754 - acc: 0.0388 - val_loss: 76.5211 - val_acc: 0.0577
Epoch 178/200
412/412 [==============================] - 0s 124us/step - loss: 79.4925 - acc: 0.0388 - val_loss: 76.4388 - val_acc: 0.0577
Epoch 179/200
412/412 [==============================] - 0s 119us/step - loss: 79.4077 - acc: 0.0388 - val_loss: 76.3551 - val_acc: 0.0577
Epoch 180/200
412/412 [==============================] - 0s 119us/step - loss: 79.3201 - acc: 0.0388 - val_loss: 76.2674 - val_acc: 0.0577
Epoch 181/200
412/412 [==============================] - 0s 124us/step - loss: 79.2291 - acc: 0.0388 - val_loss: 76.1771 - val_acc: 0.0577
Epoch 182/200
412/412 [==================

In [28]:
test=np.array([[30,1.4,1,18]])

In [30]:
test.reshape(4,)

array([30. ,  1.4,  1. , 18. ])

In [31]:
model.predict(test)

array([[10.242411]], dtype=float32)