In [1]:
import pandas as pd
import numpy as np
import sklearn 
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler
import matplotlib as plt
import keras

Using TensorFlow backend.


In [2]:
file=pd.read_csv("dataset1.csv")

In [3]:
dummies=pd.get_dummies(file.kesimpulan)

In [4]:
file1=pd.concat([file,dummies],axis='columns')

In [5]:
file1

no id    berat  tingg  umur  gender  kesibukan  berat ideal    kesimpulan  \
0       1   46.800    1.6  16.0     0.0        0.0         18.3  under weight   
1       2   47.104    1.6  16.0     0.0        0.0         18.4  under weight   
2       3   47.360    1.6  16.0     0.0        0.0         18.5        normal   
3       4   58.624    1.6  16.0     0.0        0.0         22.9        normal   
4       5   58.880    1.6  16.0     0.0        0.0         23.0   over weight   
5       6   63.744    1.6  16.0     0.0        0.0         24.9   over weight   
6       7   64.000    1.6  16.0     0.0        0.0         25.0   over weight   
7       8   76.544    1.6  16.0     0.0        0.0         29.9   over weight   
8       9   76.800    1.6  16.0     0.0        0.0         30.0   over weight   
9      10  128.000    1.6  16.0     0.0        0.0         50.0   over weight   
10     11   47.104    1.6  16.0     0.0        1.0         18.4  under weight   
11     12   47.360    1.6  16.0     0.0        1.0         18.5        normal   
12     13   58.624    1.6  16.0     0.0        1.0         22.9        normal   
13     14   58.880    1.6  16.0     0.0        1.0         23.0   over weight   
14     15   63.744    1.6  16.0     0.0        1.0         24.9   over weight   
15     16   64.000    1.6  16.0     0.0        1.0         25.0   over weight   
16     17   76.544    1.6  16.0     0.0        1.0         29.9   over weight   
17     18   76.800    1.6  16.0     0.0        1.0         30.0   over weight   
18     19  128.000    1.6  16.0     0.0        1.0         50.0   over weight   
19     20   47.104    1.6  16.0     0.0        2.0         18.4  under weight   
20     21   47.360    1.6  16.0     0.0        2.0         18.5        normal   
21     22   58.624    1.6  16.0     0.0        2.0         22.9        normal   
22     23   58.880    1.6  16.0     0.0        2.0         23.0   over weight   
23     24   63.744    1.6  16.0     0.0        2.0         24.9   over weight   
24     25   64.000    1.6  16.0     0.0        2.0         25.0   over weight   
25     26   76.544    1.6  16.0     0.0        2.0         29.9   over weight   
26     27   76.800    1.6  16.0     0.0        2.0         30.0   over weight   
27     28  128.000    1.6  16.0     0.0        2.0         50.0   over weight   
28     29   41.400    1.5  16.0     1.0        0.0         18.4  under weight   
29     30   41.625    1.5  16.0     1.0        0.0         18.5        normal   
..    ...      ...    ...   ...     ...        ...          ...           ...   
69     70      NaN    NaN   NaN     NaN        NaN          NaN           NaN   
70     71      NaN    NaN   NaN     NaN        NaN          NaN           NaN   
71     72      NaN    NaN   NaN     NaN        NaN          NaN           NaN   
72     73      NaN    NaN   NaN     NaN        NaN          NaN           NaN   
73     74      NaN    NaN   NaN     NaN        NaN          NaN           NaN   
74     75      NaN    NaN   NaN     NaN        NaN          NaN           NaN   
75     76      NaN    NaN   NaN     NaN        NaN          NaN           NaN   
76     77      NaN    NaN   NaN     NaN        NaN          NaN           NaN   
77     78      NaN    NaN   NaN     NaN        NaN          NaN           NaN   
78     79      NaN    NaN   NaN     NaN        NaN          NaN           NaN   
79     80      NaN    NaN   NaN     NaN        NaN          NaN           NaN   
80     81      NaN    NaN   NaN     NaN        NaN          NaN           NaN   
81     82      NaN    NaN   NaN     NaN        NaN          NaN           NaN   
82     83      NaN    NaN   NaN     NaN        NaN          NaN           NaN   
83     84      NaN    NaN   NaN     NaN        NaN          NaN           NaN   
84     85      NaN    NaN   NaN     NaN        NaN          NaN           NaN   
85     87      NaN    NaN   NaN     NaN        NaN          NaN           NaN   
86     88      NaN    NaN   NaN    

In [6]:
file1.head()

no id   berat  tingg  umur  gender  kesibukan  berat ideal    kesimpulan  \
0      1  46.800    1.6  16.0     0.0        0.0         18.3  under weight   
1      2  47.104    1.6  16.0     0.0        0.0         18.4  under weight   
2      3  47.360    1.6  16.0     0.0        0.0         18.5        normal   
3      4  58.624    1.6  16.0     0.0        0.0         22.9        normal   
4      5  58.880    1.6  16.0     0.0        0.0         23.0   over weight   

  kesimpulan.1  lari   diet  normal  over weight  under weight  
0          NaN   10.0   0.0       0            0             1  
1          NaN   10.0   0.0       0            0             1  
2       normal   30.0   0.0       1            0             0  
3       normal   30.0   0.0       1            0             0  
4  over weight   60.0   0.0       0            1             0

In [7]:
final=file1.drop(['no id','kesimpulan','kesimpulan.1','diet','kesibukan'],axis='columns')

In [8]:
final

berat  tingg  umur  gender  berat ideal  lari   normal  over weight  \
0    46.800    1.6  16.0     0.0         18.3   10.0       0            0   
1    47.104    1.6  16.0     0.0         18.4   10.0       0            0   
2    47.360    1.6  16.0     0.0         18.5   30.0       1            0   
3    58.624    1.6  16.0     0.0         22.9   30.0       1            0   
4    58.880    1.6  16.0     0.0         23.0   60.0       0            1   
5    63.744    1.6  16.0     0.0         24.9   60.0       0            1   
6    64.000    1.6  16.0     0.0         25.0   75.0       0            1   
7    76.544    1.6  16.0     0.0         29.9   75.0       0            1   
8    76.800    1.6  16.0     0.0         30.0   90.0       0            1   
9   128.000    1.6  16.0     0.0         50.0   90.0       0            1   
10   47.104    1.6  16.0     0.0         18.4   10.0       0            0   
11   47.360    1.6  16.0     0.0         18.5   30.0       1            0   
12   58.624    1.6  16.0     0.0         22.9   30.0       1            0   
13   58.880    1.6  16.0     0.0         23.0   50.0       0            1   
14   63.744    1.6  16.0     0.0         24.9   50.0       0            1   
15   64.000    1.6  16.0     0.0         25.0   70.0       0            1   
16   76.544    1.6  16.0     0.0         29.9   70.0       0            1   
17   76.800    1.6  16.0     0.0         30.0   85.0       0            1   
18  128.000    1.6  16.0     0.0         50.0   85.0       0            1   
19   47.104    1.6  16.0     0.0         18.4   10.0       0            0   
20   47.360    1.6  16.0     0.0         18.5   20.0       1            0   
21   58.624    1.6  16.0     0.0         22.9   20.0       1            0   
22   58.880    1.6  16.0     0.0         23.0   40.0       0            1   
23   63.744    1.6  16.0     0.0         24.9   40.0       0            1   
24   64.000    1.6  16.0     0.0         25.0   60.0       0            1   
25   76.544    1.6  16.0     0.0         29.9   60.0       0            1   
26   76.800    1.6  16.0     0.0         30.0   75.0       0            1   
27  128.000    1.6  16.0     0.0         50.0   75.0       0            1   
28   41.400    1.5  16.0     1.0         18.4   10.0       0            0   
29   41.625    1.5  16.0     1.0         18.5   30.0       1            0   
..      ...    ...   ...     ...          ...    ...     ...          ...   
69      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
70      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
71      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
72      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
73      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
74      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
75      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
76      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
77      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
78      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
79      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
80      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
81      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
82      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
83      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
84      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
85      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
86      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
87      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
88      NaN    NaN   NaN     NaN          NaN    NaN       0            0   
89

In [9]:
final=final.iloc[:55,:]

In [10]:
final

berat  tingg  umur  gender  berat ideal  lari   normal  over weight  \
0    46.800    1.6  16.0     0.0         18.3   10.0       0            0   
1    47.104    1.6  16.0     0.0         18.4   10.0       0            0   
2    47.360    1.6  16.0     0.0         18.5   30.0       1            0   
3    58.624    1.6  16.0     0.0         22.9   30.0       1            0   
4    58.880    1.6  16.0     0.0         23.0   60.0       0            1   
5    63.744    1.6  16.0     0.0         24.9   60.0       0            1   
6    64.000    1.6  16.0     0.0         25.0   75.0       0            1   
7    76.544    1.6  16.0     0.0         29.9   75.0       0            1   
8    76.800    1.6  16.0     0.0         30.0   90.0       0            1   
9   128.000    1.6  16.0     0.0         50.0   90.0       0            1   
10   47.104    1.6  16.0     0.0         18.4   10.0       0            0   
11   47.360    1.6  16.0     0.0         18.5   30.0       1            0   
12   58.624    1.6  16.0     0.0         22.9   30.0       1            0   
13   58.880    1.6  16.0     0.0         23.0   50.0       0            1   
14   63.744    1.6  16.0     0.0         24.9   50.0       0            1   
15   64.000    1.6  16.0     0.0         25.0   70.0       0            1   
16   76.544    1.6  16.0     0.0         29.9   70.0       0            1   
17   76.800    1.6  16.0     0.0         30.0   85.0       0            1   
18  128.000    1.6  16.0     0.0         50.0   85.0       0            1   
19   47.104    1.6  16.0     0.0         18.4   10.0       0            0   
20   47.360    1.6  16.0     0.0         18.5   20.0       1            0   
21   58.624    1.6  16.0     0.0         22.9   20.0       1            0   
22   58.880    1.6  16.0     0.0         23.0   40.0       0            1   
23   63.744    1.6  16.0     0.0         24.9   40.0       0            1   
24   64.000    1.6  16.0     0.0         25.0   60.0       0            1   
25   76.544    1.6  16.0     0.0         29.9   60.0       0            1   
26   76.800    1.6  16.0     0.0         30.0   75.0       0            1   
27  128.000    1.6  16.0     0.0         50.0   75.0       0            1   
28   41.400    1.5  16.0     1.0         18.4   10.0       0            0   
29   41.625    1.5  16.0     1.0         18.5   30.0       1            0   
30   51.525    1.5  16.0     1.0         22.9   30.0       1            0   
31   51.750    1.5  16.0     1.0         23.0   60.0       0            1   
32   56.025    1.5  16.0     1.0         24.9   60.0       0            1   
33   56.250    1.5  16.0     1.0         25.0   75.0       0            1   
34   67.275    1.5  16.0     1.0         29.9   75.0       0            1   
35   67.500    1.5  16.0     1.0         30.0   90.0       0            1   
36  112.500    1.5  16.0     1.0         50.0   90.0       0            1   
37   41.400    1.5  16.0     1.0         18.4   10.0       0            0   
38   41.625    1.5  16.0     1.0         18.5   30.0       1            0   
39   51.525    1.5  16.0     1.0         22.9   30.0       1            0   
40   51.750    1.5  16.0     1.0         23.0   50.0       0            1   
41   56.025    1.5  16.0     1.0         24.9   50.0       0            1   
42   56.250    1.5  16.0     1.0         25.0   70.0       0            1   
43   67.275    1.5  16.0     1.0         29.9   70.0       0            1   
44   67.500    1.5  16.0     1.0         30.0   85.0       0            1   
45  112.500    1.5  16.0     1.0         50.0   85.0       0            1   
46   41.400    1.5  16.0     1.0         18.4   10.0       0            0   
47   41.625    1.5  16.0     1.0         18.5   20.0       1            0   
48   51.525    1.5  16.0     1.0         22.9   20.0       1            0   
49   51.750    1.5  16.0     1.0         23.0   40.0       0            1   
50   56.025    1.5  16.0     1.0         24.9   40.0       0            1   
51

In [11]:
final.head()

berat  tingg  umur  gender  berat ideal  lari   normal  over weight  \
0  46.800    1.6  16.0     0.0         18.3   10.0       0            0   
1  47.104    1.6  16.0     0.0         18.4   10.0       0            0   
2  47.360    1.6  16.0     0.0         18.5   30.0       1            0   
3  58.624    1.6  16.0     0.0         22.9   30.0       1            0   
4  58.880    1.6  16.0     0.0         23.0   60.0       0            1   

   under weight  
0             1  
1             1  
2             0  
3             0  
4             0

In [13]:
ms=MinMaxScaler()
ms.fit(final.iloc[:,:6])
final=ms.transform(final.iloc[:,:6])

In [14]:
final

array([[0.06235566, 1.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.06586605, 1.        , 0.        , 0.        , 0.00315457,
        0.        ],
       [0.06882217, 1.        , 0.        , 0.        , 0.00630915,
        0.25      ],
       [0.19889145, 1.        , 0.        , 0.        , 0.14511041,
        0.25      ],
       [0.20184758, 1.        , 0.        , 0.        , 0.14826498,
        0.625     ],
       [0.25801386, 1.        , 0.        , 0.        , 0.20820189,
        0.625     ],
       [0.26096998, 1.        , 0.        , 0.        , 0.21135647,
        0.8125    ],
       [0.40581986, 1.        , 0.        , 0.        , 0.3659306 ,
        0.8125    ],
       [0.40877598, 1.        , 0.        , 0.        , 0.36908517,
        1.        ],
       [1.        , 1.        , 0.        , 0.        , 1.        ,
        1.        ],
       [0.06586605, 1.        , 0.        , 0.        , 0.00315457,
        0.        ],
       [0.06882217, 1

In [25]:
y=final[:,5]

In [26]:
y

array([0.    , 0.    , 0.25  , 0.25  , 0.625 , 0.625 , 0.8125, 0.8125,
       1.    , 1.    , 0.    , 0.25  , 0.25  , 0.5   , 0.5   , 0.75  ,
       0.75  , 0.9375, 0.9375, 0.    , 0.125 , 0.125 , 0.375 , 0.375 ,
       0.625 , 0.625 , 0.8125, 0.8125, 0.    , 0.25  , 0.25  , 0.625 ,
       0.625 , 0.8125, 0.8125, 1.    , 1.    , 0.    , 0.25  , 0.25  ,
       0.5   , 0.5   , 0.75  , 0.75  , 0.9375, 0.9375, 0.    , 0.125 ,
       0.125 , 0.375 , 0.375 , 0.625 , 0.625 , 0.8125, 0.8125])

In [42]:
x=final[:,:5]
x

array([[0.06235566, 1.        , 0.        , 0.        , 0.        ],
       [0.06586605, 1.        , 0.        , 0.        , 0.00315457],
       [0.06882217, 1.        , 0.        , 0.        , 0.00630915],
       [0.19889145, 1.        , 0.        , 0.        , 0.14511041],
       [0.20184758, 1.        , 0.        , 0.        , 0.14826498],
       [0.25801386, 1.        , 0.        , 0.        , 0.20820189],
       [0.26096998, 1.        , 0.        , 0.        , 0.21135647],
       [0.40581986, 1.        , 0.        , 0.        , 0.3659306 ],
       [0.40877598, 1.        , 0.        , 0.        , 0.36908517],
       [1.        , 1.        , 0.        , 0.        , 1.        ],
       [0.06586605, 1.        , 0.        , 0.        , 0.00315457],
       [0.06882217, 1.        , 0.        , 0.        , 0.00630915],
       [0.19889145, 1.        , 0.        , 0.        , 0.14511041],
       [0.20184758, 1.        , 0.        , 0.        , 0.14826498],
       [0.25801386, 1.        , 0.

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [44]:
x_train[1].shape

(5,)

In [45]:
x_train

array([[0.06586605, 1.        , 0.        , 0.        , 0.00315457],
       [0.        , 0.        , 0.        , 1.        , 0.00315457],
       [0.20184758, 1.        , 0.        , 0.        , 0.14826498],
       [0.11951501, 0.        , 0.        , 1.        , 0.14826498],
       [0.11951501, 0.        , 0.        , 1.        , 0.14826498],
       [0.        , 0.        , 0.        , 1.        , 0.00315457],
       [0.40581986, 1.        , 0.        , 0.        , 0.3659306 ],
       [0.25801386, 1.        , 0.        , 0.        , 0.20820189],
       [1.        , 1.        , 0.        , 0.        , 1.        ],
       [0.30138568, 0.        , 0.        , 1.        , 0.36908517],
       [0.16887991, 0.        , 0.        , 1.        , 0.20820189],
       [1.        , 1.        , 0.        , 0.        , 1.        ],
       [0.29878753, 0.        , 0.        , 1.        , 0.3659306 ],
       [0.29878753, 0.        , 0.        , 1.        , 0.3659306 ],
       [0.26096998, 1.        , 0.

In [91]:
x_train.shape

(44, 5)

In [87]:
x_train[0,:3].shape

(3,)

In [89]:
y_train[0].shape

()

In [59]:
import keras as k
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras.optimizers import adam

In [94]:
model = Sequential()
model.add(Dense(10,input_shape=(5,)))
model.add(Activation('relu'))
model.add(Dense(5,))
model.add(Activation('relu'))
model.add(Dense(1))
model.add(Activation('relu'))

In [95]:
opt = adam(lr=1e-3, decay=1e-3 / 200)
model.compile(loss="mean_absolute_percentage_error",
              optimizer=opt,
              metrics=['accuracy'])

In [96]:
model.fit(x_train, y_train, validation_data=(x_test,y_test),
epochs=200, batch_size=8)

Train on 44 samples, validate on 11 samples
Epoch 1/200
44/44 [==============================] - 0s 10ms/step - loss: 10537823.9407 - acc: 0.1591 - val_loss: 26282.9557 - val_acc: 0.0909
Epoch 2/200
44/44 [==============================] - 0s 227us/step - loss: 6088956.8505 - acc: 0.1591 - val_loss: 83.3984 - val_acc: 0.0909
Epoch 3/200
44/44 [==============================] - 0s 341us/step - loss: 2010567.0837 - acc: 0.1591 - val_loss: 87.4899 - val_acc: 0.0909
Epoch 4/200
44/44 [==============================] - 0s 250us/step - loss: 77.3922 - acc: 0.1591 - val_loss: 88.4763 - val_acc: 0.0909
Epoch 5/200
44/44 [==============================] - 0s 227us/step - loss: 78.1994 - acc: 0.1591 - val_loss: 88.5595 - val_acc: 0.0909
Epoch 6/200
44/44 [==============================] - 0s 159us/step - loss: 77.6410 - acc: 0.1591 - val_loss: 88.3720 - val_acc: 0.0909
Epoch 7/200
44/44 [==============================] - 0s 273us/step - loss: 76.5056 - acc: 0.1591 - val_loss: 88.0293 - val_acc: 

Epoch 61/200
44/44 [==============================] - 0s 205us/step - loss: 68.0615 - acc: 0.1591 - val_loss: 84.8935 - val_acc: 0.0909
Epoch 62/200
44/44 [==============================] - 0s 159us/step - loss: 68.0501 - acc: 0.1591 - val_loss: 84.8671 - val_acc: 0.0909
Epoch 63/200
44/44 [==============================] - 0s 182us/step - loss: 68.0419 - acc: 0.1591 - val_loss: 84.8406 - val_acc: 0.0909
Epoch 64/200
44/44 [==============================] - 0s 159us/step - loss: 68.0238 - acc: 0.1591 - val_loss: 84.8192 - val_acc: 0.0909
Epoch 65/200
44/44 [==============================] - 0s 182us/step - loss: 68.0129 - acc: 0.1591 - val_loss: 84.7944 - val_acc: 0.0909
Epoch 66/200
44/44 [==============================] - 0s 182us/step - loss: 67.9973 - acc: 0.1591 - val_loss: 84.7705 - val_acc: 0.0909
Epoch 67/200
44/44 [==============================] - 0s 159us/step - loss: 67.9900 - acc: 0.1591 - val_loss: 84.7507 - val_acc: 0.0909
Epoch 68/200
44/44 [============================

44/44 [==============================] - 0s 273us/step - loss: 66.4120 - acc: 0.1591 - val_loss: 83.8977 - val_acc: 0.0909
Epoch 122/200
44/44 [==============================] - 0s 182us/step - loss: 66.4044 - acc: 0.1591 - val_loss: 83.8880 - val_acc: 0.0909
Epoch 123/200
44/44 [==============================] - 0s 159us/step - loss: 66.4030 - acc: 0.1591 - val_loss: 83.8786 - val_acc: 0.0909
Epoch 124/200
44/44 [==============================] - 0s 182us/step - loss: 66.3967 - acc: 0.1591 - val_loss: 83.8699 - val_acc: 0.0909
Epoch 125/200
44/44 [==============================] - 0s 205us/step - loss: 66.3911 - acc: 0.1591 - val_loss: 83.8623 - val_acc: 0.0909
Epoch 126/200
44/44 [==============================] - 0s 205us/step - loss: 66.3882 - acc: 0.1591 - val_loss: 83.8559 - val_acc: 0.0909
Epoch 127/200
44/44 [==============================] - 0s 136us/step - loss: 66.3857 - acc: 0.1591 - val_loss: 83.8466 - val_acc: 0.0909
Epoch 128/200
44/44 [==============================] - 

Epoch 181/200
44/44 [==============================] - 0s 136us/step - loss: 65.7641 - acc: 0.1591 - val_loss: 82.9709 - val_acc: 0.0909
Epoch 182/200
44/44 [==============================] - 0s 182us/step - loss: 65.7175 - acc: 0.1591 - val_loss: 82.9239 - val_acc: 0.0909
Epoch 183/200
44/44 [==============================] - 0s 182us/step - loss: 65.6833 - acc: 0.1591 - val_loss: 82.8753 - val_acc: 0.0909
Epoch 184/200
44/44 [==============================] - 0s 182us/step - loss: 65.6367 - acc: 0.1591 - val_loss: 82.8317 - val_acc: 0.0909
Epoch 185/200
44/44 [==============================] - 0s 205us/step - loss: 65.6074 - acc: 0.1591 - val_loss: 82.7826 - val_acc: 0.0909
Epoch 186/200
44/44 [==============================] - 0s 159us/step - loss: 65.5589 - acc: 0.1591 - val_loss: 82.7401 - val_acc: 0.0909
Epoch 187/200
44/44 [==============================] - 0s 182us/step - loss: 65.5176 - acc: 0.1591 - val_loss: 82.6992 - val_acc: 0.0909
Epoch 188/200
44/44 [====================

In [118]:
test=np.array([[30,1.4,20,1,18]])

In [119]:
test.reshape(5,)

array([30. ,  1.4, 20. ,  1. , 18. ])

In [120]:
model.predict(test)

array([[8.75394]], dtype=float32)